apiVersion: v1
kind: Namespace
metadata:
  name: slotify
  labels:
    name: slotify
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: slotify-staging
  labels:
    name: slotify-staging
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: slotify-dev
  labels:
    name: slotify-dev
    environment: development